version: 2.1

jobs:

  a-main:
    docker:
      - image: alpine
    steps: 
      - checkout
      - run: "echo 'Hello from A!'"
  b-main:
    docker:
      - image: alpine
    steps: 
      - checkout
      - run: "echo 'Hello from B!'"

workflows:

  a-main:
    jobs:
      - a-main  
  b-main:
    jobs:
      - b-main