version: 2.1

setup: << pipeline.parameters.run-setup >>

orbs:
  continuation: circleci/continuation@0.2.0
  path-filtering: circleci/path-filtering@0.0.2

parameters:
  run-setup:
    type: boolean
    default: true
  run-a:
    type: boolean
    default: false
  run-b:
    type: boolean
    default: false
  run-all:
    type: boolean
    default: false

jobs:
  main:
    docker:
      - image: cimg/base:2020.01
    steps: 
      - checkout
      - run:
          command: |
            echo "What a test, you know!"
            if [ "$buildAll" = "true" ]; then ./configConstructor.sh true; fi;

      - continuation/continue:
          configuration_path: ./metaconfig.yml

  module-a:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: "echo 'Hello from module A!!'"
      - run: cat a/README.md

  module-b:
    machine: true
    steps:
      - checkout
      - run: "echo 'Hello from module B!'"
      - run: cat b/README.md

  module-b-post:
    docker:
      - image: alpine
    steps:
      - run: "echo 'Continuing module B'"
      - run: env

workflows:
  pre:
    when: << pipeline.parameters.run-setup >>
    jobs:
      - main

  module-a:
    when: 
      or: [ << pipeline.parameters.run-a >>, << pipeline.parameters.run-all >> ]
    jobs:
      - module-a
  module-b:
    when: 
      or: [<< pipeline.parameters.run-b >>, << pipeline.parameters.run-all >> ]
    jobs:
      - module-b
      - module-b-post:
          requires:
            - module-b