version: 2.1

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  main:
    docker:
      - image: cimg/base:2020.01
    steps: 
      - checkout
      - run:
          command: |
            echo "Let's check for the buildAll variable."
            env
            echo "buildAll is $buildAll"
            ./construct-config.sh $buildAll

      - continuation/continue:
          configuration_path: ./generated-config.yml

workflows:
  pre:
    jobs:
      - main